import { Network } from './networks';

/**
 * Networks supported by Web3 Gateways
 */
export type GatewayNetwork = Extract<Network,
    Network.AF_NEXUS_TESTNET |
    Network.AMOY |
    Network.ARBITRUM |
    Network.ARBITRUM_NOVA |
    Network.ARBITRUM_SEPOLIA |
    Network.AVA |
    Network.BASE |
    Network.BASE_SEPOLIA |
    Network.BEPOLIA |
    Network.BERACHAIN |
    Network.BERACHAIN_BARTIO |
    Network.BLAST |
    Network.BOB |
    Network.BOBA_BINANCE |
    Network.BOBA_BINANCE_RIALTO |
    Network.BOBA_ETHEREUM |
    Network.BOBA_SEPOLIA |
    Network.BOB_SEPOLIA |
    Network.BOB_TESTNET |
    Network.CELO |
    Network.CELO_SEPOLIA |
    Network.CFX_ESPACE |
    Network.CFX_ESPACE_TESTNET |
    Network.FLARE |
    Network.FRAXTAL |
    Network.FRAXTAL_HOODI |
    Network.GNOSIS |
    Network.GNOSIS_CHIADO_TESTNET |
    Network.GOLD_MAINNET |
    Network.HOODI |
    Network.IMMUTABLE |
    Network.IMMUTABLE_TESTNET |
    Network.INK |
    Network.INK_SEPOLIA |
    Network.INTERVAL_TESTNET |
    Network.KATANA |
    Network.KATANA_BOKUTO |
    Network.LENS |
    Network.LENS_SEPOLIA |
    Network.LINEA |
    Network.LINEA_SEPOLIA |
    Network.LISK |
    Network.LISK_SEPOLIA |
    Network.MAINNET |
    Network.MONAD |
    Network.MONAD_TESTNET |
    Network.MORPH |
    Network.MORPH_HOODI |
    Network.OMEGA_13 |
    Network.OPTIMISTIC |
    Network.OPTIMISTIC_SEPOLIA |
    Network.PLASMA |
    Network.PLASMA_TESTNET |
    Network.POLYGON |
    Network.POLYNOMIAL |
    Network.POLYNOMIAL_SEPOLIA |
    Network.RONIN |
    Network.RONIN_TESTNET |
    Network.SCROLL |
    Network.SCROLL_SEPOLIA |
    Network.SEPOLIA |
    Network.SONEIUM |
    Network.SONEIUM_MINATO |
    Network.SONIC |
    Network.SONIC_BLAZE |
    Network.SOPHON |
    Network.SOPHON_TESTNET |
    Network.STABLE_TESTNET |
    Network.STORY |
    Network.STORY_AENEID |
    Network.SWELLCHAIN |
    Network.SWELLCHAIN_SEPOLIA |
    Network.TAIKO |
    Network.TAIKO_HOODI |
    Network.TEMPO_MODERATO_TESTNET |
    Network.TEMPO_TESTNET |
    Network.UNICHAIN |
    Network.UNICHAIN_SEPOLIA |
    Network.WORLDCHAIN |
    Network.WORLDCHAIN_SEPOLIA |
    Network.ZIRCUIT |
    Network.ZIRCUIT_GARFIELD_TESTNET |
    Network.ZKSYNC |
    Network.ZKSYNC_SEPOLIA
> 